'use client'

import Link from 'next/link'
import { useState, useEffect } from 'react'
import { usePathname } from 'next/navigation'
import { useCustomerSocket } from '@/hooks/useCustomerSocket'
import { SESSION_EVENTS, INVOICE_EVENTS } from '@/lib/socket/events'
import { AlertTriangle, IndianRupee, CheckCircle2, ChevronRight } from 'lucide-react'
import { JoinRequestToast } from './JoinRequestToast'

export function SessionStatusGuard({ children }: { children: React.ReactNode }) {
  const [sessionState, setSessionState] = useState<'ACTIVE' | 'INVOICE_GENERATED' | 'COMPLETED'>('ACTIVE')
  const { on } = useCustomerSocket()
  const pathname = usePathname()
  const isReceiptOrOrdersPage = pathname === '/invoice' || pathname === '/orders'

  useEffect(() => {
    // Sync status with database on initial mount
    fetch('/api/customer/session/status')
      .then((res) => res.json())
      .then((data) => {
        if (data.success && data.sessionStatus) {
          if (data.sessionStatus === 'COMPLETED' || data.sessionStatus === 'CLOSED') {
            setSessionState('COMPLETED')
          } else if (data.sessionStatus === 'INVOICE_GENERATED') {
            setSessionState('INVOICE_GENERATED')
          } else {
            setSessionState('ACTIVE')
          }
        }
      })
      .catch((err) => console.error('[SessionStatusGuard] Initial fetch failed:', err))

    const unsubClosed = on(SESSION_EVENTS.CLOSED, () => {
      setSessionState('COMPLETED')
    })
    const unsubInvGen = on(INVOICE_EVENTS.GENERATED, () => {
      setSessionState('INVOICE_GENERATED')
    })
    const unsubInvPaid = on(INVOICE_EVENTS.PAID, () => {
      setSessionState('COMPLETED')
    })

    return () => {
      unsubClosed()
      unsubInvGen()
      unsubInvPaid()
    }
  }, [on])

  // Block access to menu/cart if session is closed or invoice is generated
  if ((sessionState === 'COMPLETED' || sessionState === 'INVOICE_GENERATED') && !isReceiptOrOrdersPage) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-4 py-12 text-center">
        <div className="w-full max-w-md rounded-2xl border border-border bg-card p-8 shadow-lg">
          <div className="mb-6 flex flex-col items-center justify-center">
            <img src="/logo.png" alt="QRDineX Logo" className="h-9 w-auto object-contain shadow-sm" />
          </div>

          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary/10 mb-6">
            {sessionState === 'COMPLETED' ? (
              <CheckCircle2 className="h-8 w-8 text-emerald-500" />
            ) : (
              <IndianRupee className="h-8 w-8 text-blue-500" />
            )}
          </div>

          <h2 className="text-2xl font-bold tracking-tight text-foreground">
            {sessionState === 'COMPLETED' ? 'Session Completed' : 'Invoice Generated'}
          </h2>

          <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
            {sessionState === 'COMPLETED'
              ? 'This dining session has been completed and finalized. Thank you for dining with us!'
              : 'The restaurant has generated your bill. Please view the invoice to make payment and finalize your session.'}
          </p>

          <div className="mt-8 flex flex-col gap-3">
            <Link
              href="/invoice"
              className="inline-flex h-11 items-center justify-center rounded-xl bg-primary text-sm font-semibold text-primary-foreground transition-all hover:bg-primary/90 active:scale-95 shadow-md"
            >
              {sessionState === 'COMPLETED' ? 'View Final Receipt' : 'View Invoice & Pay'}
            </Link>
            <Link
              href="/orders"
              className="inline-flex h-11 items-center justify-center rounded-xl border border-input bg-background text-sm font-semibold text-foreground transition-all hover:bg-muted active:scale-95"
            >
              View Order History
            </Link>
          </div>
        </div>
      </div>
    )
  }

  return (
    <>
      {sessionState === 'INVOICE_GENERATED' && (
        <Link
          href="/invoice"
          className="sticky top-0 z-50 flex items-center justify-center gap-2 bg-blue-600 px-4 py-2.5 text-center text-xs font-bold text-white shadow-md hover:bg-blue-700 transition-colors"
        >
          <IndianRupee className="h-4 w-4 shrink-0" />
          <span>Invoice generated by restaurant. Tap to view your bill & complete payment →</span>
          <ChevronRight className="h-4 w-4 shrink-0" />
        </Link>
      )}
      {sessionState === 'COMPLETED' && (
        <Link
          href="/invoice"
          className="sticky top-0 z-50 flex items-center justify-center gap-2 bg-emerald-600 px-4 py-2.5 text-center text-xs font-bold text-white shadow-md hover:bg-emerald-700 transition-colors"
        >
          <CheckCircle2 className="h-4 w-4 shrink-0" />
          <span>Dining session completed & paid. Tap to view final receipt →</span>
          <ChevronRight className="h-4 w-4 shrink-0" />
        </Link>
      )}
      {children}
      {/* JOIN REQUEST TOASTS — only visible to the HOST participant */}
      <JoinRequestToast />
    </>
  )
}
