'use client'

import Link from 'next/link'
import { useState, useEffect } from 'react'
import { useCustomerSocket } from '@/hooks/useCustomerSocket'
import { SESSION_EVENTS, INVOICE_EVENTS } from '@/lib/socket/events'
import { AlertTriangle, Receipt, CheckCircle2, ChevronRight } from 'lucide-react'

export function SessionStatusGuard({ children }: { children: React.ReactNode }) {
  const [sessionState, setSessionState] = useState<'ACTIVE' | 'INVOICE_GENERATED' | 'COMPLETED'>('ACTIVE')
  const { on } = useCustomerSocket()

  useEffect(() => {
    const unsubClosed = on(SESSION_EVENTS.CLOSED, () => {
      setSessionState('COMPLETED')
    })
    const unsubInvGen = on(INVOICE_EVENTS.GENERATED, () => {
      setSessionState('INVOICE_GENERATED')
    })
    const unsubInvPaid = on(INVOICE_EVENTS.PAID, () => {
      setSessionState('COMPLETED')
    })

    return () => {
      unsubClosed()
      unsubInvGen()
      unsubInvPaid()
    }
  }, [on])

  return (
    <>
      {sessionState === 'INVOICE_GENERATED' && (
        <Link
          href="/invoice"
          className="sticky top-0 z-50 flex items-center justify-center gap-2 bg-blue-600 px-4 py-2.5 text-center text-xs font-bold text-white shadow-md hover:bg-blue-700 transition-colors"
        >
          <Receipt className="h-4 w-4 shrink-0" />
          <span>Invoice generated by restaurant. Tap to view your bill & complete payment →</span>
          <ChevronRight className="h-4 w-4 shrink-0" />
        </Link>
      )}
      {sessionState === 'COMPLETED' && (
        <Link
          href="/invoice"
          className="sticky top-0 z-50 flex items-center justify-center gap-2 bg-emerald-600 px-4 py-2.5 text-center text-xs font-bold text-white shadow-md hover:bg-emerald-700 transition-colors"
        >
          <CheckCircle2 className="h-4 w-4 shrink-0" />
          <span>Dining session completed & paid. Tap to view final receipt →</span>
          <ChevronRight className="h-4 w-4 shrink-0" />
        </Link>
      )}
      {children}
    </>
  )
}
