'use client'

import { useState, useEffect, useCallback } from 'react'
import Link from 'next/link'
import {
  ArrowLeft,
  IndianRupee,
  CheckCircle2,
  Clock,
  UtensilsCrossed,
  Loader2,
  Building2,
  CreditCard,
  Sparkles,
} from 'lucide-react'
import { useCustomerSocket } from '@/hooks/useCustomerSocket'
import { INVOICE_EVENTS, SESSION_EVENTS } from '@/lib/socket/events'

export interface InvoiceItem {
  id: string
  itemName: string
  quantity: number
  unitPrice: number
  lineTotal: number
}

export interface InvoiceData {
  id: string
  invoiceNumber: string
  restaurantName: string
  tableNumber: number
  generatedAt: string
  paidAt: string | null
  paymentStatus: 'UNPAID' | 'PAID' | 'CANCELLED'
  paymentMethod: 'CASH' | 'UPI' | 'CARD' | 'OTHER' | null
  subtotal: number
  discountAmount: number
  taxAmount: number
  serviceCharge: number
  roundOff: number
  grandTotal: number
  notes?: string | null
  items: InvoiceItem[]
}

interface CustomerInvoiceClientProps {
  initialHasInvoice: boolean
  initialSessionStatus: string
  initialRestaurantName?: string
  initialTableNumber?: number
  initialInvoice?: InvoiceData | null
}

export function CustomerInvoiceClient({
  initialHasInvoice,
  initialSessionStatus,
  initialRestaurantName = '',
  initialTableNumber = 0,
  initialInvoice = null,
}: CustomerInvoiceClientProps) {
  const [hasInvoice, setHasInvoice] = useState<boolean>(initialHasInvoice)
  const [sessionStatus, setSessionStatus] = useState<string>(initialSessionStatus)
  const [restaurantName, setRestaurantName] = useState<string>(initialRestaurantName)
  const [tableNumber, setTableNumber] = useState<number>(initialTableNumber)
  const [invoice, setInvoice] = useState<InvoiceData | null>(initialInvoice)
  const [isLoading, setIsLoading] = useState<boolean>(false)

  const { on } = useCustomerSocket()

  const fetchInvoice = useCallback(async () => {
    setIsLoading(true)
    try {
      const res = await fetch('/api/customer/invoice')
      const data = await res.json()
      if (data.success) {
        setHasInvoice(data.hasInvoice)
        setSessionStatus(data.sessionStatus)
        if (data.restaurantName) setRestaurantName(data.restaurantName)
        if (data.tableNumber) setTableNumber(data.tableNumber)
        if (data.invoice) setInvoice(data.invoice)
      }
    } catch (e) {
      console.error('[CustomerInvoiceClient] Failed to fetch invoice:', e)
    } finally {
      setIsLoading(false)
    }
  }, [])

  // Real-time socket event handlers
  useEffect(() => {
    // 1. Invoice generated by owner
    const unsubGen = on(INVOICE_EVENTS.GENERATED, () => {
      fetchInvoice()
    })

    // 2. Invoice payment confirmed by owner
    const unsubPaid = on(INVOICE_EVENTS.PAID, (payload) => {
      setInvoice((prev) => {
        if (!prev) return prev
        return {
          ...prev,
          paymentStatus: 'PAID',
          paymentMethod: (payload.paymentMethod as 'CASH' | 'UPI' | 'CARD' | 'OTHER') || 'CASH',
          paidAt: payload.paidAt || new Date().toISOString(),
        }
      })
      setSessionStatus('COMPLETED')
    })

    // 3. Session closed/completed by owner
    const unsubClosed = on(SESSION_EVENTS.CLOSED, () => {
      setSessionStatus('COMPLETED')
    })

    return () => {
      unsubGen()
      unsubPaid()
      unsubClosed()
    }
  }, [on, fetchInvoice])

  const isSessionCompleted =
    sessionStatus === 'COMPLETED' ||
    sessionStatus === 'CLOSED' ||
    invoice?.paymentStatus === 'PAID'

  return (
    <div className="mx-auto max-w-xl px-4 pb-20 pt-4">
      {/* Header Bar */}
      <div className="mb-6 flex items-center justify-between border-b border-border/60 pb-4">
        <div className="flex items-center gap-3">
          {!isSessionCompleted ? (
            <Link
              href="/orders"
              className="flex h-10 w-10 items-center justify-center rounded-full bg-muted transition-colors hover:bg-muted/80"
              title="Back to orders"
            >
              <ArrowLeft className="h-5 w-5 text-foreground" />
            </Link>
          ) : (
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
              <CheckCircle2 className="h-6 w-6" />
            </div>
          )}
          <div>
            <h1 className="text-xl font-bold tracking-tight text-foreground">
              Customer Invoice
            </h1>
            <p className="text-xs text-muted-foreground">
              {restaurantName || 'Restaurant'} • Table {tableNumber || '—'}
            </p>
          </div>
        </div>

        {/* Live Status Pill */}
        <div>
          {isSessionCompleted ? (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-700 dark:text-emerald-400">
              <CheckCircle2 className="h-3.5 w-3.5" />
              Paid & Completed
            </span>
          ) : hasInvoice ? (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-700 dark:text-amber-400">
              <Clock className="h-3.5 w-3.5 animate-pulse" />
              Waiting for Payment
            </span>
          ) : (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-500/10 px-3 py-1 text-xs font-semibold text-blue-700 dark:text-blue-400">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating Invoice...
            </span>
          )}
        </div>
      </div>

      {/* Completion Banner */}
      {isSessionCompleted && (
        <div className="mb-6 overflow-hidden rounded-2xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/10 via-emerald-500/5 to-transparent p-6 text-center shadow-sm">
          <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-white shadow-md">
            <CheckCircle2 className="h-8 w-8" />
          </div>
          <p className="mt-1 text-sm font-semibold text-emerald-700 dark:text-emerald-400">
            ✓ Dining Session Completed
          </p>
          <div className="mt-4 rounded-xl border border-emerald-500/20 bg-background/80 p-3 text-xs text-muted-foreground backdrop-blur">
            <p className="font-medium text-foreground">Thank you for dining with us!</p>
            <p className="mt-0.5">Your session has been finalized. We hope to see you again soon.</p>
          </div>
        </div>
      )}

      {/* Waiting Screen (Invoice not generated yet) */}
      {!hasInvoice && !isSessionCompleted && (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-border/80 bg-card p-8 text-center shadow-sm">
          <div className="relative mb-4 flex h-20 w-20 items-center justify-center rounded-full bg-primary/10">
            <IndianRupee className="h-10 w-10 text-primary animate-pulse" />
            <span className="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-[10px] text-primary-foreground font-bold">
              <Sparkles className="h-3 w-3" />
            </span>
          </div>

          <h2 className="text-xl font-bold text-foreground">
            Waiting for restaurant to prepare your bill...
          </h2>
          <p className="mt-2 max-w-sm text-sm text-muted-foreground">
            The restaurant has received your bill request and is creating your finalized invoice.
          </p>

          <div className="mt-6 flex items-center gap-2 rounded-full border border-border bg-muted/50 px-4 py-2 text-xs font-medium text-muted-foreground">
            <Loader2 className="h-3.5 w-3.5 animate-spin text-primary" />
            <span>This screen will update automatically. No refresh needed.</span>
          </div>
        </div>
      )}

      {/* Invoice Content (Once generated) */}
      {hasInvoice && invoice && (
        <div className="space-y-6">
          {/* Invoice Card */}
          <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
            {/* Header info */}
            <div className="border-b border-border bg-muted/40 p-5">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2 text-primary font-bold text-base">
                    <Building2 className="h-4 w-4" />
                    {invoice.restaurantName}
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Table Number: <span className="font-semibold text-foreground">{invoice.tableNumber}</span>
                  </p>
                </div>
                <div className="text-right">
                  <span className="rounded-md bg-muted px-2.5 py-1 text-xs font-mono font-bold text-foreground">
                    {invoice.invoiceNumber}
                  </span>
                  <p className="mt-1.5 text-[11px] text-muted-foreground">
                    {new Date(invoice.generatedAt).toLocaleString([], {
                      dateStyle: 'medium',
                      timeStyle: 'short',
                    })}
                  </p>
                </div>
              </div>
            </div>

            {/* Itemized Table */}
            <div className="p-5">
              <h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">
                Ordered Items
              </h3>
              <div className="divide-y divide-border/60">
                {invoice.items.map((item) => (
                  <div key={item.id} className="flex items-center justify-between py-3 text-sm">
                    <div className="flex items-start gap-3">
                      <span className="flex h-5 min-w-[20px] items-center justify-center rounded bg-primary/10 px-1.5 text-xs font-bold text-primary">
                        {item.quantity}x
                      </span>
                      <div>
                        <p className="font-medium leading-snug text-foreground">{item.itemName}</p>
                        <p className="text-xs text-muted-foreground">
                          ₹{item.unitPrice.toFixed(2)} each
                        </p>
                      </div>
                    </div>
                    <span className="font-semibold text-foreground">
                      ₹{item.lineTotal.toFixed(2)}
                    </span>
                  </div>
                ))}
              </div>

              {/* Financial Breakdown */}
              <div className="mt-6 border-t border-border pt-4 space-y-2 text-sm">
                <div className="flex justify-between text-muted-foreground">
                  <span>Subtotal</span>
                  <span className="font-medium text-foreground">₹{invoice.subtotal.toFixed(2)}</span>
                </div>

                {invoice.discountAmount > 0 && (
                  <div className="flex justify-between text-emerald-600 dark:text-emerald-400">
                    <span>Discount</span>
                    <span className="font-medium">-₹{invoice.discountAmount.toFixed(2)}</span>
                  </div>
                )}

                {invoice.taxAmount > 0 && (
                  <div className="flex justify-between text-muted-foreground">
                    <span>Tax</span>
                    <span className="font-medium text-foreground">₹{invoice.taxAmount.toFixed(2)}</span>
                  </div>
                )}

                {invoice.serviceCharge > 0 && (
                  <div className="flex justify-between text-muted-foreground">
                    <span>Service Charge</span>
                    <span className="font-medium text-foreground">₹{invoice.serviceCharge.toFixed(2)}</span>
                  </div>
                )}

                {invoice.roundOff !== 0 && (
                  <div className="flex justify-between text-muted-foreground text-xs">
                    <span>Round Off</span>
                    <span>{invoice.roundOff > 0 ? `+₹${invoice.roundOff.toFixed(2)}` : `-₹${Math.abs(invoice.roundOff).toFixed(2)}`}</span>
                  </div>
                )}

                <div className="flex justify-between border-t border-border pt-3 text-base font-bold text-foreground">
                  <span>Grand Total</span>
                  <span className="text-lg text-primary">₹{invoice.grandTotal.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* Payment Summary Footer */}
            <div className="border-t border-border bg-muted/20 p-5">
              <h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">
                Payment Details
              </h3>
              <div className="flex flex-wrap items-center justify-between gap-2 text-sm">
                <div className="flex items-center gap-2">
                  <CreditCard className="h-4 w-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Payment Status:</span>
                  {invoice.paymentStatus === 'PAID' ? (
                    <span className="rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-bold text-emerald-700 dark:text-emerald-400">
                      PAID
                    </span>
                  ) : (
                    <span className="rounded-full bg-amber-500/10 px-2.5 py-0.5 text-xs font-bold text-amber-700 dark:text-amber-400">
                      UNPAID (Pending Owner Confirmation)
                    </span>
                  )}
                </div>

                {invoice.paymentStatus === 'PAID' && invoice.paymentMethod && (
                  <div className="text-xs text-muted-foreground">
                    Method: <span className="font-bold text-foreground">{invoice.paymentMethod}</span>
                  </div>
                )}
              </div>

              {invoice.paidAt && (
                <p className="mt-2 text-[11px] text-muted-foreground">
                  Paid at: {new Date(invoice.paidAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                </p>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
